export const ADD_COUNTRY = "ADD_COUNTRY";
export const ADD_TEST = "ADD_TEST";
export const FETCH_INFO_ABOUT_COUNTRY = "FETCH_INFO_ABOUT_COUNTRY";
export const FETCH_CLIMATE_DATA = "FETCH_CLIMATE_DATA";
export const SET_MODE = "SET_MODE";
